DoAnLapTrinhWeb2023/DoAnLapTrinhWeb2023/Models/baiViet.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnLapTrinhWeb2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class baiViet
    {
        public string maBV { get; set; }
        public string tenBV { get; set; }
        public string hinhDD { get; set; }
        public string ndTomTat { get; set; }
        public Nullable<System.DateTime> ngayDang { get; set; }
        public string noiDung { get; set; }
        public string taiKhoan { get; set; }
        public Nullable<bool> daDuyet { get; set; }
        public Nullable<int> maLoai { get; set; }
    
        public virtual taiKhoanTV taiKhoanTV { get; set; }
    }
}

DoAnLapTrinhWeb2023/DoAnLapTrinhWeb2023/Areas/Admin/Controllers/BaiVietController.cs
using DoAnLapTrinhWeb2023.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoAnLapTrinhWeb2023.Areas.Admin.Controllers
{
    public class BaiVietController : Controller
    {
        // GET: Admin/BaiViet
        BanHangOnlineEntities objBanHangOnlineEntities = new BanHangOnlineEntities();
        // GET: Admin/ProductAdmin
        public ActionResult Index(string SearchString, int? page, string curentFilter)
        {
            var listBaiViet = new List<baiViet>();
            if (SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = curentFilter;
            }
            if (!string.IsNullOrEmpty(SearchString))
            {
                //lấy ds sản phẩm theo từ khóa tìm kiếm
                listBaiViet = objBanHangOnlineEntities.baiViets.Where(n => n.tenBV.Contains(SearchString)).ToList();
            }
            else
            {
                listBaiViet = objBanHangOnlineEntities.baiViets.ToList();
            }
            ViewBag.curentFilter = SearchString;
            // sô lượng item của 1 trang = 13
            int pageSize = 13;
            int pageNumber = (page ?? 1);
            // sắp xếp theo id sản phẩm mới đưa lên đầu
            return View(listBaiViet.ToPagedList(pageNumber, pageSize));




           
        }
        [HttpGet]
        public ActionResult Create()
        {
            List<loaiSP> sp = objBanHangOnlineEntities.loaiSPs.ToList();
            ViewData["loais"] = sp;
            List<Brand> br = objBanHangOnlineEntities.Brands.ToList();
            ViewData["brand"] = br;

            return View();
        }
        [HttpPost]
        public ActionResult Create(baiViet objbaiViet)
        {
            try
            {
                //kiem tra doi tuong image co load dc hay khong
                if (objbaiViet.ImageUpload != null)
                {
                    string filename = Path.GetFileNameWithoutExtension(objbaiViet.ImageUpload.FileName);
                    string extension = Path.GetExtension(objbaiViet.ImageUpload.FileName);
                    filename = filename + "_" + long.Parse(DateTime.Now.ToString("yyyyMMddhhmmss")) + extension;
                    objbaiViet.hinhDD = filename;
                    objbaiViet.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/image/"), filename));
                }
                objBanHangOnlineEntities.baiViets.Add(objbaiViet);
                objBanHangOnlineEntities.SaveChanges();
                //neu luu thanh cong return ve trang danh sach san pham
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }
        [HttpGet]
        public ActionResult Details(string id)
        {
            var objbaiViet = objBanHangOnlineEntities.sanPhams.Where(n => n.maSP == id).FirstOrDefault();
            return View(objbaiViet);
        }


        [HttpGet]
        public ActionResult Delete(string id)
        {
            var objbaiViet = objBanHangOnlineEntities.baiViets.Where(n => n.maBV == id).FirstOrDefault();
            return View(objbaiViet);
        }
        [HttpPost]
        public ActionResult Delete(string bv, string ip)
        {
            var objsbaiViets = objBanHangOnlineEntities.baiViets.Where(n => n.maBV == bv).FirstOrDefault();
            objBanHangOnlineEntities.baiViets.Remove(objsbaiViets);
            objBanHangOnlineEntities.SaveChanges();
            return RedirectToAction("Index");
        }



        [HttpGet]
        public ActionResult Edit(string id)
        {
            var objsbaiViets = objBanHangOnlineEntities.baiViets.Where(n => n.maBV == id).FirstOrDefault();
            return View(objsbaiViets);
        }
        [HttpPost]
        public ActionResult Edit(sanPham objbaiViet)
        //phương thức đẩy ảnh 
        {
            if (objbaiViet.ImageUpload != null)
            {
                string filename = Path.GetFileNameWithoutExtension(objbaiViet.ImageUpload.FileName);
                string extension = Path.GetExtension(objbaiViet.ImageUpload.FileName);
                filename = filename + "_" + long.Parse(DateTime.Now.ToString("yyyyMMddhhmmss")) + extension;
                objbaiViet.hinhDD = filename;
                objbaiViet.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/image/"), filename));
            }
            objBanHangOnlineEntities.Entry(objbaiViet).State = EntityState.Modified;
            objBanHangOnlineEntities.SaveChanges();
            //back ve trang danh sach san pham
            return RedirectToAction("Index");
        }

    }
}

DoAnLapTrinhWeb2023/DoAnLapTrinhWeb2023/Areas/Admin/Views/BaiViet/Create.cshtml
@using DoAnLapTrinhWeb2023.Models;
@model DoAnLapTrinhWeb2023.Models.baiViet

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">
    <h2>Create</h2>

    @using (Html.BeginForm("Create", "BaiViet", FormMethod.Post, new { enctype = "multipart/form-data" }))

    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>baiViet</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.maBV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.maBV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="exampleInputEmail1">Tên bài viết</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.tenBV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tenBV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
                    <label for="exampleInputEmail1">Hình nền</label>
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.hinhDD, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.hinhDD, "", new { @class = "text-danger" })
                <input type="file" name="ImageUpload" />
            </div>
        </div>

        <div class="form-group">
            <label for="exampleInputEmail1">Nội dung tóm tắt</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.ndTomTat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ndTomTat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="exampleInputEmail1">Ngày đăng</label>               
            <div class="col-md-10">
                @Html.EditorFor(model => model.ngayDang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ngayDang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="exampleInputEmail1">Nội dung</label>               
            <div class="col-md-10">
                @Html.EditorFor(model => model.noiDung, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.noiDung, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="exampleInputEmail1">Tài khoản</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.taiKhoan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.taiKhoan, "", new { @class = "text-danger" })
            </div>
        </div>

            <div class="form-group">
                @Html.LabelFor(model => model.daDuyet, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.daDuyet)
                        @Html.ValidationMessageFor(model => model.daDuyet, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.maLoai, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.maLoai, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.maLoai, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        <a href="@Url.Action("Index","BaiViet")" class="btn btn-info">
            <i class="fa fa-backward"></i>    Quay lại
        </a>
    </div>
</div>

DoAnLapTrinhWeb2023/DoAnLapTrinhWeb2023/Areas/Admin/Views/BaiViet/Delete.cshtml
@model DoAnLapTrinhWeb2023.Models.baiViet

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">
    <h2>Xóa sản phẩm</h2>


    <div>
        <h4>baiViet</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.tenBV)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.tenBV)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.hinhDD)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.hinhDD)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ndTomTat)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ndTomTat)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ngayDang)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ngayDang)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.noiDung)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.noiDung)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.daDuyet)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.daDuyet)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.maLoai)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.maLoai)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.taiKhoanTV.matKhau)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.taiKhoanTV.matKhau)
            </dd>

        </dl>
        @using (Html.BeginForm("Delete", "BaiViet", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="form-actions no-color">
                <input type="hidden" value="@Model.maBV" name="bv" />
                <input type="submit" value="Delete" onclick="confirm('BẠN CÓ CHẮC LÀ MUỐN XÓA BÀI VIẾT KHÔNG !!!!!')" class="btn btn-sm btn-danger" /> |
                <a href="@Url.Action("Index","ProductAdmin")" class="btn btn-sm btn-info">
                    <i class="fa fa-backward"></i>    Quay lại
                </a>
            </div>
        }
    </div>
</div>

DoAnLapTrinhWeb2023/DoAnLapTrinhWeb2023/Areas/Admin/Views/BaiViet/Details.cshtml
@model DoAnLapTrinhWeb2023.Models.baiViet

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">

    <h2>Details</h2>

    <div>
        <h4>baiViet</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.tenBV)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.tenBV)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.hinhDD)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.hinhDD)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ndTomTat)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ndTomTat)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ngayDang)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ngayDang)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.noiDung)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.noiDung)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.daDuyet)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.daDuyet)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.maLoai)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.maLoai)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.taiKhoanTV.matKhau)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.taiKhoanTV.matKhau)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.maBV }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>  

DoAnLapTrinhWeb2023/DoAnLapTrinhWeb2023/Areas/Admin/Views/BaiViet/Edit.cshtml
@model DoAnLapTrinhWeb2023.Models.baiViet

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="content-wrapper">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>baiViet</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.maBV)

            <div class="form-group">
                @Html.LabelFor(model => model.tenBV, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.tenBV, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.tenBV, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.hinhDD, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.hinhDD, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.hinhDD, "", new { @class = "text-danger" })
                    <input type="file" name="ImageUpload" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ndTomTat, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ndTomTat, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ndTomTat, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ngayDang, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ngayDang, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ngayDang, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.noiDung, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.noiDung, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.noiDung, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.taiKhoan, "taiKhoan", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.taiKhoan, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.taiKhoan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.daDuyet, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.daDuyet)
                        @Html.ValidationMessageFor(model => model.daDuyet, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.maLoai, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.maLoai, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.maLoai, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

DoAnLapTrinhWeb2023/DoAnLapTrinhWeb2023/Areas/Admin/Views/BaiViet/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<DoAnLapTrinhWeb2023.Models.baiViet>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<style>
    .container {
        width: 500px;   
        margin: auto;
        text-align: center;
    }
    .pagination {
        width: 400px;
        margin-left: 50px;
    }
        .pagination a {
            display: block;
            color: black;
            float: right;
            padding: 8px 16px;
            border: 1px solid #ddd;
            text-decoration: none;
            transition: background-color .3s;
            margin: 0 4px;
        }
            .pagination a.active {
                background-color: #4CAF50;
                color: white;
            }
            .pagination a:hover:not(.active) {
                background-color: deepskyblue;
            }
</style>

<div class="content-wrapper">
  

    <p>
        <a href="@Url.Action("Create", "BaiViet")" class="btn btn-primary">
            <i class="fa fa-plus"></i> Tạo bài viết
        </a>
    </p>
    @using (Html.BeginForm("Index", "BaiViet", FormMethod.Get)) 
    {
        <p>
            Tìm kiếm sản phẩm : @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
            <input type="submit" value="Tìm kiếm" />
        </p>
    }
    <table class="table">
        <tr>
            <th>
                <p>Tên bài viết</p>
            </th>
            <th>
                <p>Hình đại diện</p>
            </th>
            <th>
                <p>Nội dung tóm tắt</p>
            </th>
            <th>
                <p>Ngày đăng</p>
            </th>
            <th>
                <p>Nội dung</p>
            </th>
            <th>
                <p>Đã duyệt</p>
            </th>
            <th>
                <p>Mã loại</p>
            </th>
            <th>
                <p>Tài khoản</p>
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.tenBV)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.hinhDD)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ndTomTat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ngayDang)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.noiDung)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.daDuyet)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.maLoai)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.taiKhoanTV.matKhau)
        </td>
        <td>
            <a href="@Url.Action("Edit", "BaiViet", new { id = item.maBV })" class="btn btn-sm btn-success">
                Edit <i class="fas fa-edit"></i>
            </a>
            <a href="@Url.Action("Details", "BaiViet", new { id = item.maBV })" class="btn btn-sm btn-info">
                Details <i class="fa fa-eye"></i>
            </a>
            <a href="@Url.Action("Delete", "BaiViet", new { id = item.maBV })" class="btn btn-sm btn-danger">
                Delete <i class="fas fa-trash-alt"></i>
            </a>
        </td>
    </tr>
        }

    </table>
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, CurrentFilter = ViewBag.CurrentFilter }))
    </div>