DoAnLapTrinhWeb2023/DoAnLapTrinhWeb2023/Controllers/NewFolder1/MouseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAnLapTrinhWeb2023.Models;
namespace DoAnLapTrinhWeb2023.Controllers
{
    public class MouseController : Controller
    {
        // GET: Mouse  BanHangOnlineEntities objBanHangOnlineEntities = new BanHangOnlineEntities();
        BanHangOnlineEntities objBanHangOnlineEntities = new BanHangOnlineEntities();
        public ActionResult Index(string tenTH)
        {
            //loc cac ten brand vat dau tu phan string 
            var objKB = objBanHangOnlineEntities.sanPhams.Where(n => n.loaiSP.loaiSP1.Equals("Chuột") && (string.IsNullOrEmpty(tenTH) || (n.Brand.tenTH.Equals(tenTH)))).ToList<sanPham>();
            ViewData["MS"] = objKB;
            //khi co ai do click vao thi no se lien tuc update
            updateBrand();
            return View(objKB);

        }
        public void updateBrand()
        {
            ViewData["up"] = objBanHangOnlineEntities.Brands.ToList();

        }
    }
}

DoAnLapTrinhWeb2023/DoAnLapTrinhWeb2023/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAnLapTrinhWeb2023.Models;
namespace DoAnLapTrinhWeb2023.Controllers
{
    public class ProductController : Controller
    {
       static BanHangOnlineEntities objBanHangOnlineEntities = new BanHangOnlineEntities();
        // GET: Product
        public ActionResult Details(String maSP)
        {
            var objSanPham = objBanHangOnlineEntities.sanPhams.Where(n => n.maSP == maSP).FirstOrDefault();
 
            return View(objSanPham);
        }
    }   
}

DoAnLapTrinhWeb2023/DoAnLapTrinhWeb2023/Views/Mouse/Index.cshtml
@using DoAnLapTrinhWeb2023.Models;

@{
    ViewBag.Title = "Index";
    List<sanPham> MS = ViewData["MS"] as List<sanPham>;
    List<Brand> BR = ViewData["up"] as List<Brand>;
}

<section class="main-content-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <!-- BSTORE-BREADCRUMB START -->
                <div class="bstore-breadcrumb">
                    <a href="index.html">Trang chủ</a>
                    <span><i class="fa fa-caret-right"></i></span>
                    <span>Bàn phím <span>
                </div>
                <!-- BSTORE-BREADCRUMB END -->
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                <!-- PRODUCT-LEFT-SIDEBAR START -->
                <div class="product-left-sidebar">
                    <!-- SINGLE SIDEBAR ENABLED FILTERS START -->
                    <!-- SINGLE SIDEBAR ENABLED FILTERS END -->
                    <!-- SINGLE SIDEBAR CATEGORIES START -->
                    <div class="product-single-sidebar">
                        <span class="sidebar-title">Danh mục</span>
                        <ul>
                            @foreach (var item in BR.Skip(3).Take(3))
                            {

                                <li>
                                    <label class="cheker">
                                        <input type="checkbox" name="categories" />
                                        <span></span>
                                    </label>
                                    <a href="@Url.Action("Index" ,"Mouse", new {tenTH=item.tenTH})">@item.tenTH</a>
                                </li>
                            }

                        </ul>
                    </div>



                   
                    <!-- SINGLE SIDEBAR PROPERTIES END -->
                </div>

            </div>
            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                <div class="right-all-product">
                    <!-- PRODUCT-CATEGORY-HEADER START -->
                    <div class="product-category-header">
                        <div class="category-header-image">
                            @*<img width="500px" height="425px" src="~/image/bigmouse.png" alt="category-header" />*@

                        </div>
                    </div>
                    <!-- PRODUCT-CATEGORY-HEADER END -->
                    <div class="product-category-title">
                        <!-- PRODUCT-CATEGORY-TITLE START -->
                        <!-- PRODUCT-CATEGORY-TITLE END -->
                    </div>
                    <div class="product-shooting-area">

                        <!-- PRODUCT-SHOOTING-RESULT START -->
                        <div class="product-shooting-result">


                            <div class="showing-next-prev">


                            </div>
                        </div>
                        <!-- PRODUCT-SHOOTING-RESULT END -->
                    </div>
                </div>
                <!-- ALL GATEGORY-PRODUCT START -->
                <div class="all-gategory-product">
                    <div class="row">
                        <ul class="gategory-product">
                            @foreach (var item in MS)
                            {<!-- SINGLE ITEM START -->
                                <li class="gategory-product-list  col-md-4 col-sm-6 col-xs-12">
                                    <div class="single-product-item">
                                        <div class="product-image">
                                            <a href="@Url.Action("Details","Product", new {maSP = item.maSP } )"><img src="@item.hinhDD" alt="product-image" /></a>
                                            <a href="single-product.html" class="new-mark-box">new</a>
                                            <div class="overlay-content">
                                                <ul>
                                                    <li><a href="@Url.Action("Details","Product", new {maSP = item.maSP } )" title="Quick view"><i class="fa fa-search"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div class="product-info">
                                            <div class="customar-comments-box">
                                                <div class="rating-box">
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star"></i>
                                                    <i class="fa fa-star-half-empty"></i>
                                                    <i class="fa fa-star-half-empty"></i>
                                                </div>
                                                <div class="review-box">
                                                    <span>1 Review(s)</span>
                                                </div>
                                            </div>
                                            @Html.ActionLink(item.tenSP, "Details", "Product", new { maSP = item.maSP }, null)

                                            <div class="price-box">
                                                <span class="price">@item.giaBan  ₫</span>

                                            </div>
                                        </div>
                                    </div>
                                </li>
                                <!-- SINGLE ITEM END -->}


                        </ul>
                    </div>
                </div>
                <!-- ALL GATEGORY-PRODUCT END -->
                <!-- PRODUCT-SHOOTING-RESULT START -->
                <!-- PRODUCT-SHOOTING-RESULT END -->
            </div>
        </div>
    </div>
</section>