DoAnLapTrinhWeb2023/DoAnLapTrinhWeb2023/Areas/Admin/Controllers/ProductAdminController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAnLapTrinhWeb2023.Models;
using PagedList;

namespace DoAnLapTrinhWeb2023.Areas.Admin.Controllers
{
    public class ProductAdminController : Controller
    {
  
        BanHangOnlineEntities objBanHangOnlineEntities = new BanHangOnlineEntities();
        // GET: Admin/ProductAdmin
        public ActionResult Index(string SearchString ,int? page , string curentFilter)
        {
            var listsanPham = new List<sanPham>();
            if (SearchString != null)
            {
                page = 1;
            }
          else
            {
                SearchString = curentFilter; 
            }
            if (!string.IsNullOrEmpty(SearchString))
            {
                //lấy ds sản phẩm theo từ khóa tìm kiếm
                listsanPham = objBanHangOnlineEntities.sanPhams.Where(n => n.tenSP.Contains(SearchString)).ToList();
            }
            else
            {
                listsanPham = objBanHangOnlineEntities.sanPhams.ToList();
            }
            ViewBag.curentFilter = SearchString;
            // sô lượng item của 1 trang = 13
            int pageSize = 13;
            int pageNumber = (page ?? 1);
            // sắp xếp theo id sản phẩm mới đưa lên đầu
            return View(listsanPham.ToPagedList(pageNumber, pageSize));




            //if (SearchString !=null)
            //{
            //    var listSanPhams = objBanHangOnlineEntities.sanPhams.Where(n => n.tenSP.ToUpper().Contains(SearchString)).ToList();
            //    return View(listSanPhams.ToList());

            //}

            var listSanPham = objBanHangOnlineEntities.sanPhams.ToList();
            return View(listSanPham);
        }
        [HttpGet]
        public ActionResult Create()
        {
            List<loaiSP> sp = objBanHangOnlineEntities.loaiSPs.ToList();
            ViewData["loaisp"] = sp;
            List<Brand> br = objBanHangOnlineEntities.Brands.ToList();
            ViewData["brand"] = br;
         
            return View();
        }
        [HttpPost]
        public ActionResult Create(sanPham objsanPham, sanPham dh)
        {
            dh.ngayDang = DateTime.Now;
            if (ModelState.IsValid)
            {
                sanPham sp = new sanPham
                { 
                //taiKhoan = "minh",
                daDuyet = false,
                ngayDang = dh.ngayDang,
                nhaSanXuat = "VietNam",
                dvt = "cái",
                };              
        }          
            try
            {         
                //kiem tra doi tuong image co load dc hay khong
                if (objsanPham.ImageUpload != null)
                {
                    string filename = Path.GetFileNameWithoutExtension(objsanPham.ImageUpload.FileName);
                    string extension = Path.GetExtension(objsanPham.ImageUpload.FileName);
                    filename = filename + "_" + long.Parse(DateTime.Now.ToString("yyyyMMddhhmmss")) + extension;
                    objsanPham.hinhDD = filename;
                    objsanPham.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/image/"), filename));
                    
                }
                objBanHangOnlineEntities.sanPhams.Add(objsanPham);
                objBanHangOnlineEntities.SaveChanges();
                //neu luu thanh cong return ve trang danh sach san pham
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
            }
        [HttpGet]
        public ActionResult Details(string id)
        {
            var objsanPhams = objBanHangOnlineEntities.sanPhams.Where(n => n.maSP == id).FirstOrDefault();
            return View(objsanPhams);
        }


        [HttpGet]
        public ActionResult Delete(string id)
        {
            var objsanPhams = objBanHangOnlineEntities.sanPhams.Where(n => n.maSP == id).FirstOrDefault();
            return View(objsanPhams);
        }
        [HttpPost]
        public ActionResult Delete(string sp, string ip)
        {
            var objsanPhams = objBanHangOnlineEntities.sanPhams.Where(n => n.maSP == sp).FirstOrDefault();
            objBanHangOnlineEntities.sanPhams.Remove(objsanPhams);
            objBanHangOnlineEntities.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit (string id)
        {
            var objsanPhams = objBanHangOnlineEntities.sanPhams.Where(n => n.maSP == id).FirstOrDefault();
            return View(objsanPhams);
        }
        [HttpPost]  
        public ActionResult Edit(sanPham objsanPham)
        //phương thức đẩy ảnh 
        {
            if (objsanPham.ImageUpload != null)
            {
                string filename = Path.GetFileNameWithoutExtension(objsanPham.ImageUpload.FileName);
                string extension = Path.GetExtension(objsanPham.ImageUpload.FileName);
                filename = filename + "_" + long.Parse(DateTime.Now.ToString("yyyyMMddhhmmss")) + extension;
                objsanPham.hinhDD = filename;
                objsanPham.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/image/"), filename));
            }
            objBanHangOnlineEntities.Entry(objsanPham).State = EntityState.Modified;
            objBanHangOnlineEntities.SaveChanges();
            //back ve trang danh sach san pham
            return RedirectToAction("Index");
        }
    }
 }

DoAnLapTrinhWeb2023/DoAnLapTrinhWeb2023/Areas/Admin/Views/ProductAdmin/Create.cshtml
@using DoAnLapTrinhWeb2023.Models;
@model DoAnLapTrinhWeb2023.Models.sanPham

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    List<loaiSP> LSP = ViewData["loaisp"]  as List<loaiSP>;
    List<Brand> BR = ViewData["brand"] as List<Brand>;
}
<div class="content-wrapper">
<h2>Tạo mới</h2>

@using (Html.BeginForm("Create", "ProductAdmin",FormMethod.Post, new {  enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.maSP, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.maSP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.maSP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.tenSP, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.tenSP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.tenSP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.hinhDD, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*@Html.EditorFor(model => model.hinhDD, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.hinhDD, "", new { @class = "text-danger" })
            <input type="file" name="ImageUpload" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ndTomTat, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ndTomTat, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ndTomTat, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.ngayDang, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ngayDang, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ngayDang, "", new { @class = "text-danger" })
        </div>
    </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.loaiHang, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.loaiHang, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.loaiHang, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.noiDung, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.noiDung, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.noiDung, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.taiKhoan, "taiKhoan", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.taiKhoan, new { htmlAttributes = new { @class = "form-control" } })
       
            @Html.ValidationMessageFor(model => model.taiKhoan, "", new { @class = "text-danger" })
        </div>
    </div>
    @*<div class="form-group">
        @Html.LabelFor(model => model.daDuyet, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.daDuyet)
                @Html.ValidationMessageFor(model => model.daDuyet, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.giaBan, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.giaBan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.giaBan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.giamGia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.giamGia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.giamGia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.maLoai, "maLoai", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.maLoai, new { htmlAttributes = new { @class = "form-control" } })
         
            @Html.ValidationMessageFor(model => model.maLoai, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.nhaSanXuat, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.nhaSanXuat, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nhaSanXuat, "", new { @class = "text-danger" })
        </div>
    </div>*@

    @*<div class="form-group">
        @Html.LabelFor(model => model.dvt, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.dvt, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.dvt, "", new { @class = "text-danger" })
        </div>
    </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.maTH, "maTH", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.maTH, new { htmlAttributes = new { @class = "form-control" } })
            @*@Html.DropDownListFor(model => model.maTH, new SelectList(BR, "maTh", "tenTH"), new { @class = "form-control" })*@ 
            @Html.ValidationMessageFor(model => model.maTH, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Tạo"class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    <a href="@Url.Action("Index","ProductAdmin")" class="btn btn-info">
        <i class="fa fa-backward"></i>    Quay lại 
    </a>
</div>
    </div>

DoAnLapTrinhWeb2023/DoAnLapTrinhWeb2023/Areas/Admin/Views/ProductAdmin/Delete.cshtml
@model DoAnLapTrinhWeb2023.Models.sanPham

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">
    <h2>Xóa sản phẩm</h2>
    <div>
        
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.tenSP)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.tenSP)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.hinhDD)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.hinhDD)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ndTomTat)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ndTomTat)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ngayDang)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ngayDang)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.loaiHang)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.loaiHang)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.noiDung)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.noiDung)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.daDuyet)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.daDuyet)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.giaBan)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.giaBan)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.giamGia)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.giamGia)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.nhaSanXuat)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.nhaSanXuat)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.dvt)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.dvt)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Brand.tenTH)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Brand.tenTH)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.loaiSP.loaiSP1)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.loaiSP.loaiSP1)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.taiKhoanTV.matKhau)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.taiKhoanTV.matKhau)
            </dd>

        </dl>

        @using (Html.BeginForm("Delete", "ProductAdmin", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
    <div class="form-actions no-color">
        <input type="hidden" value="@Model.maSP" name="sp" />
        <input type="submit" value="Delete" onclick="confirm('BẠN CÓ CHẮC LÀ MUỐN XÓA SẢN PHẨM KHÔNG !!!!!')" class="btn btn-sm btn-danger" /> |
        <a href="@Url.Action("Index","ProductAdmin")" class="btn btn-sm btn-info">
            <i class="fa fa-backward"></i>    Quay lại
        </a>
    </div>
        }
    </div>
</div>  

DoAnLapTrinhWeb2023/DoAnLapTrinhWeb2023/Areas/Admin/Views/ProductAdmin/Edit.cshtml
@model DoAnLapTrinhWeb2023.Models.sanPham

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">

    <h2>Edit</h2>

    @using (Html.BeginForm("Edit", "ProductAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))

    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>sanPham</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.maSP)

            <div class="form-group">
                @Html.LabelFor(model => model.tenSP, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.tenSP, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.tenSP, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.hinhDD, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.hinhDD, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.hinhDD, "", new { @class = "text-danger" })
                    <input type="file" name="ImageUpload" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ndTomTat, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ndTomTat, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ndTomTat, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ngayDang, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ngayDang, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ngayDang, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.loaiHang, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.loaiHang, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.loaiHang, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.noiDung, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.noiDung, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.noiDung, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.taiKhoan, "taiKhoan", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.taiKhoan, new { htmlAttributes = new { @class = "form-control" } })

                    @Html.ValidationMessageFor(model => model.taiKhoan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.daDuyet, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.daDuyet)
                        @Html.ValidationMessageFor(model => model.daDuyet, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.giaBan, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.giaBan, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.giaBan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.giamGia, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.giamGia, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.giamGia, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.maLoai, "maLoai", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.maLoai, new { htmlAttributes = new { @class = "form-control" } })

                    @Html.ValidationMessageFor(model => model.maLoai, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.nhaSanXuat, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nhaSanXuat, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nhaSanXuat, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.dvt, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.dvt, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.dvt, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.maTH, "maTH", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.maTH, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.maTH, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>   
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

DoAnLapTrinhWeb2023/DoAnLapTrinhWeb2023/Areas/Admin/Views/ProductAdmin/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<DoAnLapTrinhWeb2023.Models.sanPham>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<style>
    .container {
  width: 500px;
  margin: auto;
  text-align: center;
}
.pagination {
  width: 400px;
  margin-left: 50px;
}
    .pagination a {
        display: block;
        color: black;
        float: right;   
        padding: 8px 16px;
        border: 1px solid #ddd;
        text-decoration: none;
        transition: background-color .3s;
        margin: 0 4px;
    }
 
.pagination a.active {
    background-color: #4CAF50;
    color: white;
}
 
.pagination a:hover:not(.active) {
  background-color: deepskyblue;
}

</style>


<div class="content-wrapper">
  
        
    <p>
        <a href="@Url.Action("Create", "ProductAdmin")" class="btn btn-primary">
            <i class="fa fa-plus"></i> Tạo sản phẩm 
        </a>    
    </p>
    @using (Html.BeginForm("Index", "ProductAdmin", FormMethod.Get))
    {
   <p>
       Tìm kiếm sản phẩm : @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
       <input type="submit" value="Tìm kiếm"/>
   </p>
    }
    <table class="table">
        <tr>
            <th>
                <p>Tên sản phẩm</p>
            </th>
            <th>
                <p>File hình</p>
            </th>
            <th>
                <p>Nội dung tóm tắt</p>
            </th>                        
            <th>            
                <p>Giá bán</p>
            </th>
            <th>
                <p>Thương hiệu</p>
            </th>
            <th>
                <p>Loại sản phẩm</p>
            </th>          
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td> 
                    @Html.DisplayFor(modelItem => item.tenSP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.hinhDD)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ndTomTat)
                </td>          
                <td>
                    @Html.DisplayFor(modelItem => item.giaBan)
                </td>            
                <td>
                    @Html.DisplayFor(modelItem => item.Brand.tenTH)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.loaiSP.loaiSP1)
                </td>
               
                <td>
                    <a href="@Url.Action("Edit", "ProductAdmin", new { id = item.maSP })" class="btn btn-sm btn-success"> 
                        Edit <i class="fas fa-edit"></i>
                    </a>
                    <a href="@Url.Action("Details", "ProductAdmin", new { id = item.maSP })" class="btn btn-sm btn-info">
                        Details <i class="fa fa-eye"></i>
                    </a>
                    <a href="@Url.Action("Delete", "ProductAdmin", new { id = item.maSP })" class="btn btn-sm btn-danger">
                        Delete <i class="fas fa-trash-alt"></i>
                    </a>          
                </td>
            </tr>
        }
    </table>
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page , CurrentFilter =  ViewBag.CurrentFilter }))
</div>